### ISSUE TITLE
Vue in the frontend

### ISSUE THREAD

**Issue by garethworld** [HashandSalt/kirby3-snipcart#1]
Wonderful idea for a plugin!

Would you would consider not using Vue in the frontend? This seems opinionated - a bit like wordpress including jQuery by default i.e not very kirby like. It seems like a heavy framework just to (presumably) make some ajax calls.

**Comment by HashandSalt** [comment]
Unfourtunatly, Snipcart requires Vue. Looking at the API ... MAYBE it can all be done with PHP. But thats not going to happen any time soon im afraid.
